# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------
spring:
  application:
    name: "mysql-sys"
  profiles:
    active: "default"
  config:
    import: [ ]
  main:
    web-application-type: servlet
    banner-mode: log
    allow-bean-definition-overriding: true
    allow-circular-references: false
    log-startup-info: true
    cloud-platform: none
    lazy-initialization: false
    register-shutdown-hook: true
    sources: [ ]
  banner:
    location: "classpath:/META-INF/banner.txt"
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://192.168.31.165:3306/sys?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai"
    username: "root"
    password: "root"
  pid:
    file: "/var/run/${spring.application.name}/pid"
    fail-on-write-error: false
  autoconfigure:
    exclude:
      - "org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration"
      - "org.springframework.boot.autoconfigure.jdbc.JndiDataSourceAutoConfiguration"

# ----------------------------------------------------------------------------------------------------------------------
# 服务器
# ----------------------------------------------------------------------------------------------------------------------
server:
  port: 18330
  servlet:
    context-path: "/"

# ----------------------------------------------------------------------------------------------------------------------
# 日志
# ----------------------------------------------------------------------------------------------------------------------
logging:
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}]%-5level %logger{72}[%L] - %msg%n"
    file: "${logging.pattern.console}"
  level:
    "root": info
    "com.github.yingzhuo.mysqlsys": trace
    "com.github.yingzhuo.mysqlsys.model.mapper": debug
    "org.springframework": info
    "org.springframework.boot.context.ApplicationPidFileWriter": off
    "org.apache.catalina": warn
    "com.zaxxer.hikari": warn

# ----------------------------------------------------------------------------------------------------------------------
# MyBatis / MyBatis-Plus
# ----------------------------------------------------------------------------------------------------------------------
mybatis-plus:
  global-config:
    banner: false
  mapperLocations:
    - "classpath*:/mybatis-mapper/**/*Mapper.xml"
  type-aliases-package: "com.github.yingzhuo.mysqlsys.model"

# ----------------------------------------------------------------------------------------------------------------------
# Actuator
# ----------------------------------------------------------------------------------------------------------------------
management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    env:
      show-values: always
  info:
    env:
      enabled: true
    git:
      enabled: true
      mode: full
    build:
      enabled: true
    os:
      enabled: true
    java:
      enabled: true
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include: "*"
