# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------
spring:
  application:
    name: "mysql-sys"
  profiles:
    active: "default"
  config:
    import: [ ]
  main:
    web-application-type: servlet
    banner-mode: off
    allow-bean-definition-overriding: true
    allow-circular-references: false
    log-startup-info: true
    cloud-platform: none
    lazy-initialization: false
    register-shutdown-hook: true
    sources: [ ]
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://192.168.31.165:3306/sys?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai"
    username: "root"
    password: "root"
  autoconfigure:
    exclude:
      - "org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration"
      - "org.springframework.boot.autoconfigure.jdbc.JndiDataSourceAutoConfiguration"

# ----------------------------------------------------------------------------------------------------------------------
# 服务器
# ----------------------------------------------------------------------------------------------------------------------
server:
  port: 18330
  servlet:
    context-path: "/"

# ----------------------------------------------------------------------------------------------------------------------
# 日志
# ----------------------------------------------------------------------------------------------------------------------
logging:
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}]%-5level %logger{72}[%L] - %msg%n"
    file: "${logging.pattern.console}"
  level:
    "root": info
    "com.github.yingzhuo.mysqlsys": trace
    "com.github.yingzhuo.mysqlsys.model.mapper": debug
    "org.springframework": warn
    "org.apache.catalina": warn
    "com.zaxxer.hikari": warn

# ----------------------------------------------------------------------------------------------------------------------
# MyBatis / MyBatis-Plus
# ----------------------------------------------------------------------------------------------------------------------
mybatis-plus:
  global-config:
    banner: false
  mapperLocations:
    - "classpath*:/mybatis-mapper/**/*Mapper.xml"
  type-aliases-package: "com.github.yingzhuo.mysqlsys.model"
